# -*- coding: utf-8 -*-
"""Sistem_Rekomendasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOANy5VqMuqfqklPwEKwIl3sx142tewH

# Proyek System Recomendation - Supermarket Rekomendasi

- **Nama:** Nur Adilah
- **Email:** nuradilah@students.usu.ac.id
- **ID Dicoding:** MC319D5X0793 NUR ADILAH

# Import Library
"""

!pip install implicit==0.7.0
print("Library 'implicit' berhasil diinstal.")

# Import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from scipy.sparse import coo_matrix
import implicit
from sklearn.metrics import mean_squared_error, precision_score, recall_score
import warnings
warnings.filterwarnings('ignore')

"""# Load Dataset"""

# load dataset
supermarket = pd.read_csv('/content/supermarket_dataset.csv')

supermarket

"""# Data Understanding"""

print("Data shape:", supermarket.shape)

print("Data Info:")
supermarket.info()

print("\nStatistik Deskriptif:")
supermarket.describe()

print("\nUnique Product Lines:", supermarket['Product line'].nunique())
print("Unique Customer Types:", supermarket['Customer type'].unique())

# Visualisasi distribusi Product line (produk terjual terbanyak)
plt.figure(figsize=(9, 6))
sns.countplot(data=supermarket, x='Product line', order=supermarket['Product line'].value_counts().index, palette='viridis')
plt.title('Distribusi Jumlah Transaksi per Product Line')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(10, 3))

# Distribusi Customer Type
sns.countplot(data=supermarket, x='Customer type', ax=axes[0])
axes[0].set_title('Distribusi Customer Type')

# Distribusi Gender
sns.countplot(data=supermarket, x='Gender', ax=axes[1])
axes[1].set_title('Distribusi Gender')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Boxplot Unit price per Product line
sns.boxplot(data=supermarket, x='Product line', y='Unit price', ax=axes[0])
axes[0].set_title('Distribusi Unit Price per Product Line')
axes[0].tick_params(axis='x', rotation=45)

# Boxplot Rating per Product line
sns.boxplot(data=supermarket, x='Product line', y='Rating', ax=axes[1])
axes[1].set_title('Distribusi Rating per Product Line')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# Histogram Quantity dan Total transakasi (gross income)
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

sns.histplot(supermarket['Quantity'], bins=20, kde=False, ax=axes[0])
axes[0].set_title('Distribusi Quantity Produk Terjual')

sns.histplot(supermarket['gross income'], bins=30, kde=True, ax=axes[1])
axes[1].set_title('Distribusi Total Transaksi')

plt.tight_layout()
plt.show()

"""# Data Preparation"""

# Konversi tipe data 'Date' dan 'Time'
supermarket['Date'] = pd.to_datetime(supermarket['Date'])
supermarket['Time'] = pd.to_datetime(supermarket['Time'], format='%I:%M:%S %p').dt.time

print("Datasetail setelah konversi tipe data:")
print(supermarket.info())

# Content-Based Filtering Preparation (CBF)
# Membuat DataFrame produk unik dengan fitur yang digunakan
df_product = supermarket[['Product line', 'Rating', 'Unit price']].drop_duplicates().reset_index(drop=True)

# Mengabungkan fitur menjadi string untuk TF-IDF
df_product['features'] = df_product['Product line']  + ' ' + df_product['Rating'].astype(str) + ' ' + df_product['Unit price'].astype(str)

# Collaborative Filtering Preparation (CF)
# Buat CustomerID dari gabungan Customer type dan Gender (karena data tidak ada user id asli)
supermarket['CustomerID'] = supermarket['Customer type'] + '_' + supermarket['Gender']

# Mapping user dan product ke index integer
user_ids = supermarket['CustomerID'].unique()
product_ids = supermarket['Product line'].unique()

user_to_idx = {user: idx for idx, user in enumerate(user_ids)}
product_to_idx = {prod: idx for idx, prod in enumerate(product_ids)}

# Buat sparse matrix user-product berdasarkan Quantity (bisa juga Total)
rows = supermarket['CustomerID'].map(user_to_idx)
cols = supermarket['Product line'].map(product_to_idx)
data = supermarket['Quantity']

sparse_user_product = coo_matrix((data, (rows, cols)), shape=(len(user_ids), len(product_ids)))

"""# Modeling

### Content-Based Filtering (CBF)
"""

# Menerapkan TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df_product['features'])

# Menunjukkan seberapa mirip setiap produk satu sama lain berdasarkan fitur-fitur yang digunakan
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Fungsi pencarian untuk menghasilkan rekomendasi produk serupa menggunakan skor kemiripan konten yang sudah dihitung sebelumnya.
def recommend_product_based(product_index, top_n=5):
  similiar_scores = list(enumerate(cosine_sim[product_index]))
  similiar_scores = sorted(similiar_scores, key=lambda x: x[1], reverse=True)
  similiar_scores = similiar_scores[1:top_n+1]
  product_indices = [i[0] for i in similiar_scores]
  return df_product.iloc[product_indices]

# Tes Model
recommend_product_based(5)

"""### Collaborative Filtering (CF)"""

# Collaborative Filtering dengan Cosine Similarity (Item-Based)
cf_pivot = supermarket.pivot_table(index='CustomerID', columns='Product line', values='Quantity', aggfunc='sum').fillna(0)

cf_similarity = cosine_similarity(cf_pivot.T)
cf_similarity_df = pd.DataFrame(cf_similarity, index=cf_pivot.columns, columns=cf_pivot.columns)

# fungsi untuk menghasilkan rekomendasi menggunakan model CF
def recommend_cf(product_line, top_n=5):
    if product_line not in cf_similarity_df.columns:
        return []
    similar_items = cf_similarity_df[product_line].sort_values(ascending=False)[1:top_n+1]
    return similar_items

# Tes model
recommend_cf("Electronic accessories", top_n=5)

"""# Evaluasi

### Content-Based Filtering
"""

# Membuat fungsi untuk menghitung presisi model

def precision_at_k_cbf(product_index, k=5):
    target_product = df_product.iloc[product_index]
    target_category = target_product['Product line']

    recommended_items_df = recommend_product_based(product_index, top_n=k)

    # Hitung berapa banyak rekomendasi yang memiliki kategori yang sama
    relevant_recommended_count = recommended_items_df['Product line'].eq(target_category).sum()

    # Hitung Precision@K
    precision = relevant_recommended_count / k if k > 0 else 0

    return precision

precisions = [precision_at_k_cbf(i, k=5) for i in df_product.index]
average_precision_cbf = np.mean(precisions)

print(f'\nPrecision Content-Based Filtering (based on category): {average_precision_cbf:.2f}')

"""### Collaborative Filtering

"""

def evaluate_cf_topk(k=5):
    total_precision = 0
    total_recall = 0
    total_items = 0

    for product in cf_similarity_df.index:
        recommended = recommend_cf(product, top_n=k).index.tolist()
        relevant_items = [p for p in cf_similarity_df.columns if p != product]

        if len(relevant_items) == 0:
          continue

        retrieved_relevant = [p for p in recommended if p in relevant_items]

        precision = len(retrieved_relevant) / k if k > 0 else 0
        recall = len(retrieved_relevant) / len(relevant_items)

        total_precision += precision
        total_recall += recall
        total_items += 1

    avg_precision = total_precision / total_items if total_items > 0 else 0
    avg_recall = total_recall / total_items if total_items > 0 else 0

    return avg_precision, avg_recall, k

avg_precision, avg_recall, k_val = evaluate_cf_topk(k=5)

print(f"\nEvaluasi Collaborative Filtering (Top-{k_val})")
print(f"Precision@{k_val}: {avg_precision:.2f}")
print(f"Recall@{k_val}: {avg_recall:.2f}")