# -*- coding: utf-8 -*-
"""Sistem_Rekomendasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOANy5VqMuqfqklPwEKwIl3sx142tewH

# Proyek System Recomendation - Supermarket Rekomendasi

- **Nama:** Nur Adilah
- **Email:** nuradilah@students.usu.ac.id
- **ID Dicoding:** MC319D5X0793 NUR ADILAH

Pertama install terlebih dahulu library implicit
"""

!pip install implicit==0.7.0
print("Library 'implicit' berhasil diinstal.")

"""# Import Library

Mengimport beberapa ibrary yang di perlukan
"""

# Import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from scipy.sparse import coo_matrix
import implicit
from sklearn.metrics import mean_squared_error, precision_score, recall_score
import warnings
warnings.filterwarnings('ignore')

"""# Load Dataset"""

# load dataset
supermarket = pd.read_csv('/content/supermarket_dataset.csv')

supermarket

"""**Insight:**

Terdat 1000 baris dalam dataset ini dan 17 kolom yaitu:

- 'InvoiceID': ID Transaksi, menunjukkan transaksi unik, akan digunakan untuk Collaborative Filtering.
- 'Branch' & 'City': Cabang toko yang masing-masing berada di kota yang berbeda.
- 'Customer type': Ada dua jenis pelanggan yaitu `Member` dan `Normal`.
- 'Gender': Jenis kelamin pelanggan antara laki-laki (`Male`) dan perempuan (`Female`).
- 'Product Line': Kategori produk yang dibeli, misalnya Health and beauty, Electronic accesories, Home and lifestyle, dll. Menunjukkan jenis produk yang dibeli, penting untuk Content-based Filtering.
- 'Unit Price': Harga satuan produk.
- 'Quantity': Jumlah item yang dibeli
- 'Total': Total transaksi (Unit price x Quantity).
- 'Date' & 'Time': waktu transaksi.
- 'Payment': Metode pembayaran, yang terdapat tiga metode digunakan: `Cash`, `Credit card`, dan `Ewallet`.
- 'Rating': Penilaian pelanggan terhadap transaksi. Dapat digunakan sebagai implicit feedback atau relevansi produk.

# Data Understanding
"""

print("Data shape:", supermarket.shape)

"""Kode tersebut memberikan informasi bahwa terdapa 1000 baris dan 17 kolom pada dataset"""

print("Data Info:")
supermarket.info()

"""Kode tersebut bertujuan untuk menampilkan informasi umum dari dataset `supermarket`, seperti jumlah baris, kolom, tipe data tiap kolom, dan jumlah nilai non-null. Hal ini penting untuk memahami struktur data sebelum melakukan analisis lebih lanjut."""

print("\nStatistik Deskriptif:")
supermarket.describe()

"""Kode diatas digunakan untuk menampilkan ringkasan statistik deskriptif dari fitur numerik dalam dataset, seperti nilai mean, standar deviasi, nilai minimum dan maksimum, serta kuartil. Tujuannya adalah untuk mendapatkan gambaran awal mengenai distribusi data."""

# Melihat Jumlah Nilai Unik pada Fitur Kategorikal
print("\nUnique Product Lines:", supermarket['Product line'].nunique())
print("Unique Customer Types:", supermarket['Customer type'].unique())

"""Kode diatas digunakan untuk menghitung jumlah nilai unik pada beberapa kolom kategorikal penting, yaitu:
- `Product line`: jenis produk yang dijual,
- `Customer type`: jenis pelanggan

Informasi ini berguna untuk memahami keberagaman kategori dalam dataset.
"""

# Visualisasi distribusi Product line (produk terjual terbanyak)
plt.figure(figsize=(9, 6))
sns.countplot(data=supermarket, x='Product line', order=supermarket['Product line'].value_counts().index, palette='viridis')
plt.title('Distribusi Jumlah Transaksi per Product Line')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Visualisasi ini digunakan untuk melihat distribusi jumlah produk yang terjual berdasarkan kategori `Product line`.
Plot ini membantu mengidentifikasi kategori produk apa yang paling banyak atau paling sedikit dibeli oleh pelanggan.
"""

fig, axes = plt.subplots(1, 2, figsize=(10, 3))

# Distribusi Customer Type
sns.countplot(data=supermarket, x='Customer type', ax=axes[0])
axes[0].set_title('Distribusi Customer Type')

# Distribusi Gender
sns.countplot(data=supermarket, x='Gender', ax=axes[1])
axes[1].set_title('Distribusi Gender')

plt.tight_layout()
plt.show()

"""Pada bagian ini ditampilkan dua visualisasi:

1. **Customer Type**: Menunjukkan sebaran jumlah pelanggan berdasarkan jenisnya (misalnya: Member dan Normal).
2. **Gender**: Menampilkan jumlah pelanggan berdasarkan jenis kelamin (Pria dan Wanita).

Kedua visualisasi ini membantu kita memahami demografi pelanggan yang dilayani oleh supermarket.
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Boxplot Unit price per Product line
sns.boxplot(data=supermarket, x='Product line', y='Unit price', ax=axes[0])
axes[0].set_title('Distribusi Unit Price per Product Line')
axes[0].tick_params(axis='x', rotation=45)

# Boxplot Rating per Product line
sns.boxplot(data=supermarket, x='Product line', y='Rating', ax=axes[1])
axes[1].set_title('Distribusi Rating per Product Line')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""Bagian ini mencakup dua visualisasi:

1. **Distribusi Rating**: Menampilkan sebaran rating yang diberikan oleh pelanggan, untuk mengetahui tingkat kepuasan pelanggan terhadap produk atau layanan.
2. **Rata-rata Harga Produk per Product Line**: Menampilkan rata-rata harga unit produk berdasarkan kategori `Product line`, yang membantu dalam melihat kategori mana yang memiliki harga rata-rata tertinggi atau terendah.

Kedua visualisasi ini memberikan wawasan mengenai persepsi pelanggan dan nilai jual dari masing-masing kategori produk.
"""

# Histogram Quantity dan Total transakasi (gross income)
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

sns.histplot(supermarket['Quantity'], bins=20, kde=False, ax=axes[0])
axes[0].set_title('Distribusi Quantity Produk Terjual')

sns.histplot(supermarket['gross income'], bins=30, kde=True, ax=axes[1])
axes[1].set_title('Distribusi Total Transaksi')

plt.tight_layout()
plt.show()

"""Visualisasi ini terdiri dari dua histogram:

1. **Quantity**: Menampilkan distribusi jumlah produk yang dibeli dalam satu transaksi.
   Ini berguna untuk mengetahui apakah pelanggan cenderung membeli dalam jumlah sedikit atau banyak.

2. **Gross Income**: Menunjukkan distribusi pendapatan kotor (`gross income`) per transaksi.
   Dengan menambahkan garis KDE, kita bisa memahami pola umum nilai transaksi di supermarket.

# Data Preparation

Dataset memiliki kolom `Date` dan `Time` yang masih berupa string. Pada tahap ini, kedua kolom tersebut dikonversi ke format datetime dan time Python agar lebih mudah diproses saat analisis waktu atau pembuatan fitur waktu tambahan. Kemudian di cek kembali tipe data menggunakan `supermaket.info()`
"""

# Konversi tipe data 'Date' dan 'Time'
supermarket['Date'] = pd.to_datetime(supermarket['Date'])
supermarket['Time'] = pd.to_datetime(supermarket['Time'], format='%I:%M:%S %p').dt.time

print("Datasetail setelah konversi tipe data:")
print(supermarket.info())

"""**Content-Based Filtering (CBF) preparation**

Kode dibawah tujuannya untuk membangun sistem rekomendasi berbasis konten, dibuat DataFrame berisi produk unik dan fitur-fitur yang akan digunakan, yaitu:
- `Product line`: kategori produk,
- `Rating`: penilaian pelanggan terhadap produk,
- `Unit price`: harga satuan produk.

Langkah ini penting untuk membangun representasi produk dalam sistem rekomendasi.
"""

# Membuat DataFrame produk unik dengan fitur yang digunakan
df_product = supermarket[['Product line', 'Rating', 'Unit price']].drop_duplicates().reset_index(drop=True)

"""Kemudian menggabungkan fitur menjadi string untuk tahap TF-IDF, dan di implementasikan dengan kode dibawah ini."""

# Mengabungkan fitur menjadi string untuk TF-IDF
df_product['features'] = df_product['Product line']  + ' ' + df_product['Rating'].astype(str) + ' ' + df_product['Unit price'].astype(str)

"""Kemudian dilakukan proses vektorisasi menggunakan TF-IDF (Term Frequency-Inverse Document Frequency). Vektor hasil TF-IDF ini kemudian digunakan untuk menghitung kemiripan antar produk, yang menjadi dasar rekomendasi."""

# Menerapkan TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df_product['features'])

"""**Collaborative Filtering (CF) Preparation**

Membuat kolom 'CustomerID' baru dalam DataFrame supermarket dengan menggabungkan 'Customer type' dan 'Gender'.
"""

# Buat CustomerID dari gabungan Customer type dan Gender (karena data tidak ada user id asli)
supermarket['CustomerID'] = supermarket['Customer type'] + '_' + supermarket['Gender']

"""Kemudian dilakukan mapping antara ID pelanggan unik ('CustomerID') dan ID produk unik ('Product line') ke dalam bentuk indeks integer berurutan dengan kode di bawah ini."""

# Mapping user dan product ke index integer
user_ids = supermarket['CustomerID'].unique()
product_ids = supermarket['Product line'].unique()

user_to_idx = {user: idx for idx, user in enumerate(user_ids)}
product_to_idx = {prod: idx for idx, prod in enumerate(product_ids)}

"""Kode dibawah ini untuk membuat sparse matrix user-product berdasarkan Quantity (bisa juga Total)"""

# Buat sparse matrix user-product berdasarkan Quantity (bisa juga Total)
rows = supermarket['CustomerID'].map(user_to_idx)
cols = supermarket['Product line'].map(product_to_idx)
data = supermarket['Quantity']

sparse_user_product = coo_matrix((data, (rows, cols)), shape=(len(user_ids), len(product_ids)))

"""# Modeling

### Content-Based Filtering (CBF)

Menunjukkan seberapa mirip setiap produk satu sama lain berdasarkan fitur-fitur yang digunakan
"""

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

"""Menggunakan fungsi pencarian (atau fungsi rekomendasi) untuk menghasilkan rekomendasi produk serupa menggunakan skor kemiripan konten yang sudah dihitung sebelumnya."""

# Fungsi pencarian untuk menghasilkan rekomendasi produk serupa menggunakan skor kemiripan konten yang sudah dihitung sebelumnya.
def recommend_product_based(product_index, top_n=5):
  similiar_scores = list(enumerate(cosine_sim[product_index]))
  similiar_scores = sorted(similiar_scores, key=lambda x: x[1], reverse=True)
  similiar_scores = similiar_scores[1:top_n+1]
  product_indices = [i[0] for i in similiar_scores]
  return df_product.iloc[product_indices]

# Tes Model
recommend_product_based(5)

"""Setelah model di tes, dapat dilihat output yang di hasilkan merupakan produk-produk yang paling mirip (serupa) dengan produk yang memiliki indeks ke-5 dalam DataFrame

### Collaborative Filtering (CF)

Mempersiapkan dan membangunan model Collaborative Filtering berbasis Item (Item-Based) menggunakan Cosine Similarity  untuk mempersiapkan data interaksi user-produk dan menghitung kemiripan antar produk menggunakan Cosine Similarity sebagai langkah awal dalam membangun model Collaborative Filtering berbasis Item.
"""

# Collaborative Filtering dengan Cosine Similarity (Item-Based)
cf_pivot = supermarket.pivot_table(index='CustomerID', columns='Product line', values='Quantity', aggfunc='sum').fillna(0)

cf_similarity = cosine_similarity(cf_pivot.T)
cf_similarity_df = pd.DataFrame(cf_similarity, index=cf_pivot.columns, columns=cf_pivot.columns)

"""Pada kode dibawah ini kita menggunakan fungsi  untuk menghasilkan rekomendasi pada model Collaborative Filtering berbasis Item yang telah dibangun sebelumnya."""

# fungsi untuk menghasilkan rekomendasi menggunakan model CF
def recommend_cf(product_line, top_n=5):
    if product_line not in cf_similarity_df.columns:
        return []
    similar_items = cf_similarity_df[product_line].sort_values(ascending=False)[1:top_n+1]
    return similar_items

# Tes model
recommend_cf("Electronic accessories", top_n=5)

"""Kemudian model di tes pada kode diatas dan menghasilkan  daftar 5 produk yang paling mirip dengan "Electronic accessories" berdasarkan pola pembelian kolaboratif user, beserta skor kemiripan Cosine-nya.

# Evaluasi

### Content-Based Filtering

Evaluasi Content-Based Filtering. Metrik evaluasi yang digunakan untuk menilai performa model Content-Based Filtering (CBF) adalah Precision@K. Dengan membuat fungsi pada kode dibawah ini.
"""

# Membuat fungsi untuk menghitung presisi model

def precision_at_k_cbf(product_index, k=5):
    target_product = df_product.iloc[product_index]
    target_category = target_product['Product line']

    recommended_items_df = recommend_product_based(product_index, top_n=k)

    # Hitung berapa banyak rekomendasi yang memiliki kategori yang sama
    relevant_recommended_count = recommended_items_df['Product line'].eq(target_category).sum()

    # Hitung Precision@K
    precision = relevant_recommended_count / k if k > 0 else 0

    return precision

"""Kemudian menghitung metrik precision dengan kode dibawah."""

precisions = [precision_at_k_cbf(i, k=5) for i in df_product.index]
average_precision_cbf = np.mean(precisions)

print(f'\nPrecision Content-Based Filtering (based on category): {average_precision_cbf:.2f}')

"""Evaluasi model Content-Based Filtering (CBF) menggunakan Precision@5 menunjukkan hasil rata-rata sebesar 0.84, dengan definisi relevansi berdasarkan kesamaan kategori produk (Product line).

### Collaborative Filtering

Evaluasi Collaborative Filtering (CF) menggunakan beberapa metrik yang umum untuk mengevaluasi sistem rekomendasi dalam skenario Top-K recommendation dengan menggunakan metrik evaluasi precision dan recall.

Kemudian membuat fungsi untuk menghitung precision dan recall
"""

def evaluate_cf_topk(k=5):
    total_precision = 0
    total_recall = 0
    total_items = 0

    for product in cf_similarity_df.index:
        recommended = recommend_cf(product, top_n=k).index.tolist()
        relevant_items = [p for p in cf_similarity_df.columns if p != product]

        if len(relevant_items) == 0:
          continue

        retrieved_relevant = [p for p in recommended if p in relevant_items]

        precision = len(retrieved_relevant) / k if k > 0 else 0
        recall = len(retrieved_relevant) / len(relevant_items)

        total_precision += precision
        total_recall += recall
        total_items += 1

    avg_precision = total_precision / total_items if total_items > 0 else 0
    avg_recall = total_recall / total_items if total_items > 0 else 0

    return avg_precision, avg_recall, k

"""Lalu menghitung precision dan recall"""

avg_precision, avg_recall, k_val = evaluate_cf_topk(k=5)

print(f"\nEvaluasi Collaborative Filtering (Top-{k_val})")
print(f"Precision@{k_val}: {avg_precision:.2f}")
print(f"Recall@{k_val}: {avg_recall:.2f}")

"""Evaluasi model Collaborative Filtering (CF) menggunakan metrik Average Precision@5 dan Average Recall@5 menunjukkan hasil sempurna, yaitu 1.00."""